routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Route::middleware(['auth', 'verified', 'locale'])->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.index');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::delete('/profile/avatar', [ProfileController::class, 'destroyAvatar'])->name('profile.avatar.destroy');

    Route::get('profile/update-password', [ProfileController::class, 'updatePassword'])->name('profile.update-password');
    Route::get('profile/delete', [ProfileController::class, 'delete'])->name('profile.delete');

    Route::view('/dashboard', 'dashboard')->name('dashboard');
    Route::view('/video', 'video')->name('video');
});

require __DIR__ . '/auth.php';

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use App\Http\Utils\FilesUtils;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Http\UploadedFile;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileDoesNotExist;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileIsTooBig;

class User extends Authenticatable implements HasMedia, MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;
    use InteractsWithMedia;
    public const MEDIA_AVATAR = 'avatar';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'last_name',
        'email',
        'picture',
        'locale',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function getAvatarAttribute(): ?string
    {
        $img = $this->getFirstMediaUrl(self::MEDIA_AVATAR);
        return $img ? secure_url($img) : null;
    }

    /**
     * @param UploadedFile $file
     * @return void
     * @throws FileDoesNotExist
     * @throws FileIsTooBig
     */
    public function setAvatarAttribute(UploadedFile $file): void
    {
        $this->addMedia($file)->toMediaCollection(self::MEDIA_AVATAR);
    }

    public function registerMediaCollections(): void
    {
        $this
            ->addMediaCollection(self::MEDIA_AVATAR)
            ->singleFile()
            ->acceptsMimeTypes(FilesUtils::IMAGE_MIMETYPES);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfileUpdateRequest;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\View\View;
use function Illuminate\Events\queueable;

class ProfileController extends Controller
{
    /**
     * Display the user's profile form.
     */
    public function edit(Request $request): View
    {
        return view('profile.profile', [
            'user' => $request->user(),
        ]);
    }

    /**
     * Display the user's profile form.
     */
    public function updatePassword(Request $request): View
    {
        return view('profile.update-password', [
            'user' => $request->user(),
        ]);
    }

    /**
     * Display the user's profile form.
     */
    public function delete(Request $request): View
    {
        return view('profile.delete', [
            'user' => $request->user(),
        ]);
    }

    /**
     * Update the user's profile information.
     */
    public function update(ProfileUpdateRequest $request): RedirectResponse
    {
        /** @var User $user */
        $user = auth()->user();
        $user->fill($request->validated());

        $avatar = $this->prepareValidatedGetAvatar($request->validated());
        isset($avatar) && $user->avatar = $avatar;

        if ($user->isDirty('email')) {
            $user->email_verified_at = null;
        }
        $user->save();

        return Redirect::back()->with('status', 'profile-updated');
    }

    /**
     * Delete the user's account.
     */
    public function destroy(Request $request): RedirectResponse
    {
        $request->validateWithBag('userDeletion', [
            'password' => ['required', 'current_password'],
        ]);

        $user = $request->user();

        Auth::logout();

        $user->delete();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return Redirect::to('/');
    }

    /**
     * Delete the user's account.
     */
    public function destroyAvatar(): RedirectResponse
    {
        /** @var User $user */
        $user = auth()->user();

        $user->deletePreservingMedia();

        return Redirect::back()->with('status', 'profile-updated');
    }



    private function prepareValidatedGetAvatar(array $validated): ?UploadedFile
    {
        $avatar = isset($validated['avatar']) && $validated['avatar'] instanceof UploadedFile
            ? $validated['avatar']
            : null;

        unset($validated['avatar']);

        return $avatar;
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
	<x-container>

		<x-topbar class="mb-8">
			<x-slot:title>
				{{ __('Dashboard') }}
			</x-slot:title>
		</x-topbar>

		Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit vel eveniet, maxime impedit cupiditate doloribus
		suscipit sint temporibus rerum, labore cumque autem alias. Laudantium non a aperiam officia eos modi minima optio,
		voluptate quibusdam iure dicta nulla aliquid aspernatur minus molestias, id quae perferendis repellat rerum, est
		doloremque fugiat praesentium. Dicta in ipsam delectus facilis corporis similique possimus perferendis saepe,
		consequatur quam aliquid. Ullam quibusdam porro incidunt libero dolorum odio voluptate ipsum quia aut quas sed
		perferendis nemo tempora magnam animi non ea accusantium a atque quidem, eveniet fuga et quo? Illo at eius ipsa cumque
		itaque architecto! Eaque, harum. Porro commodi rem aspernatur earum, illo corrupti totam ipsum, ducimus, eius
		doloribus culpa voluptate esse dolorum laudantium veniam laboriosam expedita aperiam numquam id iste impedit! Quam
		voluptatem natus iusto dolorum atque libero numquam, illum magnam architecto, sapiente omnis quidem ipsam voluptas eos
		nihil sed officiis aliquam! Aperiam tenetur similique sequi dolores doloribus totam, sunt nihil. Aspernatur fuga
		corrupti magni quae tempora quasi consequatur at. Odit laborum exercitationem quod rerum ducimus ipsa ullam, quas non
		ipsam magni ex placeat repellendus qui, ad laboriosam sequi quae in! Sint incidunt quas temporibus voluptates ratione,
		repellendus odio est numquam nulla sapiente sit natus obcaecati accusantium fugiat qui enim sequi. Voluptates
		reprehenderit nulla quos temporibus fuga maxime voluptate accusantium rerum cumque voluptatem quia consequuntur
		quaerat dignissimos, harum incidunt. In suscipit autem quae, ex animi necessitatibus magnam quisquam maiores quas
		alias amet officiis provident fugit harum ab nemo repudiandae explicabo libero iste expedita quo? Doloremque sunt nam
		laudantium maxime error aspernatur at rerum, voluptate incidunt consequuntur, ratione cumque culpa in atque
		architecto, magni fugiat facilis ipsam. Consequatur vitae neque ducimus repellat deserunt id non rem maxime nisi sint
		blanditiis repellendus nulla quia eum dolorem labore, numquam minima, qui voluptates? Nobis temporibus unde quia
		provident ab in ex quam impedit nostrum distinctio illo officiis, vero aliquid laborum beatae architecto incidunt?
		Animi aspernatur facere possimus ex dicta numquam vero, porro quisquam incidunt, sunt aliquid vitae necessitatibus
		dolorem optio nisi quam, ipsum nobis atque corporis perferendis cupiditate. Quas animi aliquam dolorum repellat optio
		impedit natus facilis, necessitatibus dicta magni at quaerat dolores nisi distinctio dolorem repellendus praesentium
		iusto sit eos ipsum voluptas nam quia? Hic ullam culpa nam commodi nostrum repellat amet assumenda quibusdam, nemo
		asperiores quisquam inventore vel sint harum vero perspiciatis ut dolorem alias modi doloremque non! Nam repellendus
		quidem sapiente sequi minus officia, odio ducimus ea itaque asperiores similique, placeat ipsam doloribus quae! Dicta
		iusto consectetur temporibus quas repellendus optio rem amet, beatae sint in eveniet ullam totam cumque? Nobis quidem
		labore laborum aspernatur odio sequi quos rerum atque itaque assumenda, recusandae fuga ratione consequatur corrupti
		et esse, aliquid, saepe quo excepturi sed? Ratione voluptatem numquam voluptatum necessitatibus corporis?
		Reprehenderit, velit omnis! Non est magnam natus animi fuga consectetur, sapiente excepturi ut quaerat cumque
		laudantium quasi eum facilis quos! Quos eius excepturi voluptatem. Maiores, culpa. Possimus, eos? Sit cumque nemo,
		aliquid ipsam beatae temporibus quisquam ut ipsa cupiditate nam a hic unde perspiciatis consequuntur vero quibusdam
		qui quia voluptatem explicabo eos similique dolorum. Earum rerum quaerat quas et minima obcaecati placeat totam hic
		pariatur soluta ab enim ullam repudiandae eveniet harum veritatis quibusdam incidunt ipsam expedita, id quos ducimus
		esse veniam illo? Illum laudantium quae consequuntur nam, pariatur nesciunt molestiae praesentium enim eos! Ipsum
		voluptates unde adipisci exercitationem, harum, qui omnis magni quod similique reiciendis dolorem? Laboriosam,
		incidunt dicta rerum libero optio harum quos explicabo voluptatibus eveniet quas veritatis quo facilis itaque?
		Pariatur mollitia, accusamus eos harum quia saepe, incidunt molestias nulla laboriosam dignissimos, quisquam tenetur
		repudiandae. Incidunt, corrupti iure, qui quae aperiam exercitationem temporibus possimus odio in explicabo pariatur
		fuga error nemo omnis nisi unde consectetur, velit ex eius molestiae eligendi. Repudiandae nulla quo est. Expedita
		ipsa architecto voluptate vero ut minima aliquid in odit molestiae dolor, tempore harum, voluptatibus, distinctio quas
		sit placeat temporibus. Vitae, incidunt ea. Exercitationem ratione unde, voluptatum accusantium perspiciatis officiis
		delectus dicta quis blanditiis impedit optio molestiae obcaecati quidem reiciendis sunt maxime in quae laboriosam
		porro sequi illo ullam rerum. Ducimus suscipit consectetur, explicabo illum odio nemo officiis sequi blanditiis
		laboriosam, dicta enim atque. Mollitia vel excepturi necessitatibus dolore ut unde consequatur cupiditate reiciendis
		porro blanditiis, quibusdam doloribus, molestiae autem? Aliquam eos molestiae minima nisi eligendi! Harum ipsum labore
		vel iure incidunt sequi voluptas illo obcaecati eos animi. Quo repellat officia est voluptate facere saepe? Amet culpa
		sit dolores beatae veritatis maxime consequuntur sed temporibus! Perspiciatis omnis dolorum mollitia porro! Amet,
		impedit possimus soluta ut, a consectetur officiis minima debitis ea facere aperiam sit esse adipisci eaque
		consequuntur. Eius necessitatibus modi, odit rerum laboriosam quo impedit officiis? Similique, recusandae minus
		mollitia incidunt aperiam ullam aliquid ducimus nulla, facere, maiores ad sit voluptas exercitationem sequi ab dolore
		quasi provident accusamus iusto assumenda quos corrupti explicabo. Veritatis omnis fugiat expedita fuga reiciendis.
		Fuga quibusdam nam maxime aliquam perspiciatis, eaque inventore ad praesentium omnis vel excepturi voluptas libero!
		Eaque voluptate obcaecati ipsam id, blanditiis quibusdam laboriosam voluptatem vero quaerat rem velit non dignissimos
		laborum libero dolor. Delectus, totam. Fuga, possimus excepturi sint ut similique quibusdam accusantium nostrum veniam
		iure qui aut odio explicabo animi eos. Repudiandae minima nulla, architecto accusamus, illum esse officiis labore
		quisquam sapiente, nemo quaerat quasi sit! Inventore a soluta at, veritatis illum voluptate obcaecati. Ut delectus
		eaque libero harum, optio nesciunt itaque perspiciatis voluptas fuga provident ducimus esse nisi dolorem facilis
		assumenda saepe ullam sit quia magni. Sequi, eum dolor itaque, vel eius fugit quod hic odio optio est quis accusamus
		deleniti expedita accusantium molestias doloremque possimus dolore similique illum deserunt distinctio. Sit ipsum, ut
		minus facere molestias magnam beatae mollitia iure voluptatem, officiis dolorem. Earum labore placeat repellendus
		similique ratione nihil harum laudantium consequatur! Esse eos aperiam amet reprehenderit nihil adipisci veniam
		quibusdam tempora ratione voluptates. Debitis excepturi deleniti repudiandae deserunt maxime vitae ea pariatur
		voluptatibus optio rem, cum nulla modi amet suscipit, quis totam eaque, autem eos. Exercitationem et dicta itaque
		sapiente delectus totam distinctio perspiciatis enim, accusantium dignissimos accusamus quos suscipit repudiandae eos
		illum laborum aliquid.

	</x-container>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="csrf-token" content="{{ csrf_token() }}">

	<title>{{ config('app.name', 'Laravel') }}</title>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.js"
		integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>
	<link href="{{ env('MEDIAHUB_HOST') }}/theme/pub/view/css/shmedia.css" rel="stylesheet">
	<script src="{{ env('MEDIAHUB_HOST') }}/js/shmedia1.js?v=0.02"></script>

	@vite(['resources/css/app.scss', 'resources/js/app.js'])
</head>

<script>
	document.addEventListener('alpine:init', () => {
		Alpine.data('global', () => ({
			isOpenedMobileMenu: false,
		}))
	})
</script>

<body
	class="flex min-h-screen flex-col bg-dark bg-texture-1 pt-[60px] font-sans text-sm font-normal text-light antialiased"
	x-data="global" :class="{ 'overflow-y-hidden': isOpenedMobileMenu }">

	<x-circle class="opacity-30" id="circle1" />
	<x-circle class="opacity-30" id="circle2" />

	@include('layouts.header.header')

	<div class="grid grid-cols-1 sm:grid-cols-[250px_1fr]">
		@include('layouts.sidebar.sidebar')

		<main class="overflow-y-hidden py-12">
			{{ $slot }}
		</main>
	</div>

	{{-- <link href="https://cdnjs.cloudflare.com/ajax/libs/cropper/2.3.3/cropper.css" rel="stylesheet"> --}}
</body>

</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="csrf-token" content="{{ csrf_token() }}">

	<title>{{ config('app.name', 'Laravel') }}</title>

	@vite(['resources/css/app.scss', 'resources/js/app.js'])
</head>

<body class="h-[100dvh] overflow-hidden bg-dark bg-texture-1 font-sans text-sm font-normal text-light">
	@include('vendor.lara-izitoast.toast')
	<x-circle class="opacity-30" id="circle1" />
	<x-circle class="opacity-30" id="circle2" />

	<div class="col flex h-full">
		<div class="hidden sm:block sm:w-1/4 md:w-1/3 lg:w-1/2">
			<picture>
				<source srcset="/images/auth-bg/auth-bg.avif" type="image/avif">
				<source srcset="/images/auth-bg/auth-bg.webp" type="image/webp">
				<img class="h-full w-full object-cover" src="/images/auth-bg/auth-bg.jpg" alt="auth backbrount">
			</picture>
		</div>
		<div class="flex h-full flex-grow flex-col justify-center sm:w-3/4 md:w-2/3 lg:w-1/2" x-data="{

    currentLocale: '',
    setInitialLocale() {
        const currentUrl = new URL(window.location.href);
        this.currentLocale = currentUrl.searchParams.has('locale') ? currentUrl.searchParams.get('locale') : '{{ App::currentLocale() }}'
        currentUrl.searchParams.set('locale', this.currentLocale)
        window.history.replaceState({}, '', currentUrl.toString());
    },
    changeLocale(event) {
        const currentUrl = new URL(window.location.href);
        currentUrl.searchParams.set('locale', event.detail)
        window.history.replaceState({}, '', currentUrl.toString());
        window.location.reload()
    }
}"
			x-init="setInitialLocale">
			{{-- language switcher --}}
			<x-language-switcher class="r-0 sticky top-0 mx-6 my-3 ml-auto w-[max-content]" small ::currentLocale="currentLocale"
				x-on:change-locale="changeLocale" />

			{{-- Content --}}
			<div class="overflow-y-auto px-5 py-[5vh] sm:px-10">
				{{ $slot }}
			</div>
		</div>
	</div>
</body>

</html>

resources/views/layouts/header/header.blade.php
@php
	$userName = ucfirst(Auth::user()->name);
	$maxLength = 15;
	if (strlen($userName) > $maxLength) {
	    $userName = substr($userName, 0, $maxLength) . '...';
	}
@endphp

<header class="fixed left-0 top-0 z-50 flex h-[60px] w-full items-center border-b border-primary-200 backdrop-blur-sm">
	<div class="flex w-full justify-between px-4 align-middle">
		{{-- Logo --}}
		<a class="flex items-center justify-center" href="{{ route('dashboard') }}">
			logo
		</a>

		{{-- settings --}}
		<div class="flex items-center gap-2">

			{{-- Dropdown --}}
			<div class="hidden sm:flex sm:items-center">
				<x-dropdown align="right" width="w-[max-content]">
					<x-slot name="trigger">
						<button
							class="inline-flex items-center px-3 py-2 text-gray-300 transition duration-150 ease-linear hover:text-white">
							<div class="flex items-center">
								@if (Auth::user()->avatar)
									<img class="mr-2 h-8 w-8 rounded-full border border-primary-200 object-cover"
										src="{{ asset(Auth::user()->avatar) }}" alt="avatar">
								@endif

								{{ $userName }}
							</div>

							<div class="ml-1">
								<svg class="h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
									<path fill-rule="evenodd"
										d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
										clip-rule="evenodd" />
								</svg>
							</div>
						</button>
					</x-slot>

					<x-slot name="content">
						<nav class="grid gap-4 px-4 py-4">
							<x-link class="w-full text-left" :href="route('profile.index')">
								{{ __('Profile') }}
							</x-link>

							<form method="POST" action="{{ route('logout') }}">
								@csrf

								<x-link class="w-full text-left" :href="route('logout')" component="button">
									{{ __('Log Out') }}
								</x-link>
							</form>
						</nav>
					</x-slot>
				</x-dropdown>
			</div>

			{{-- Hamburger --}}
			<button class="relative flex h-8 w-8 items-center justify-center focus:outline-none sm:hidden"
				x-on:click.away="isOpenedMobileMenu=false" x-on:click="isOpenedMobileMenu=!isOpenedMobileMenu">
				<span class="absolute block h-0.5 w-2/3 transform bg-white transition ease-linear"
					:class="{ 'rotate-45': isOpenedMobileMenu, ' -translate-y-1.5': !isOpenedMobileMenu }"></span>
				<span class="absolute block h-0.5 w-2/3 transform bg-white transition ease-linear"
					:class="{ 'opacity-0': isOpenedMobileMenu }"></span>
				<span class="absolute block h-0.5 w-2/3 transform bg-white transition ease-linear"
					:class="{ '-rotate-45': isOpenedMobileMenu, ' translate-y-1.5': !isOpenedMobileMenu }"></span>
			</button>
		</div>
	</div>

	{{-- Mobile Menu --}}
	<div
		class="l-0 fixed top-0 z-40 flex h-[100dvh] w-full -translate-x-full flex-col border-primary-200 bg-dark px-4 py-5 transition duration-200 min-[500px]:w-[300px] min-[500px]:border-r sm:hidden"
		:class="{ 'translate-x-0': isOpenedMobileMenu }" x-on:click.stop>

		{{-- Close button --}}
		<button class="absolute right-4 top-4 hidden h-8 w-8 items-center justify-center focus:outline-none max-[500px]:flex"
			x-on:click.stop="isOpenedMobileMenu=false">
			<span class="absolute block h-0.5 w-2/3 rotate-45 transform bg-white transition ease-linear"></span>
			<span class="absolute block h-0.5 w-2/3 -rotate-45 transform bg-white transition ease-linear"></span>
		</button>

		{{-- Profile --}}
		<div
			class="hover-icon hover:bg-secondary-100 dark:hover:bg-secondary-700 flex min-h-[72px] flex-row items-center gap-4 hover:bg-opacity-30 dark:hover:bg-opacity-30">
			@if (Auth::user()->avatar)
				<img class="mr-2 h-8 w-8 rounded-full border border-primary-200 object-cover"
					src="{{ asset(Auth::user()->avatar) }}" alt="avatar">
			@else
				<div
					class="bg-primary-600 flex h-10 w-10 items-center justify-center rounded-full bg-primary-200 text-base font-bold tracking-[0.15px] text-white">
					{{ strtoupper(substr(Auth::user()->name, 0, 1)) }}
				</div>
			@endif
			<div class="flex flex-grow flex-col">
				<p class="tracking-[.03125em]">{{ $userName }}</p>
				<span class="text-sm tracking-[0.25px]">{{ Auth::user()->email }}</span>
			</div>
		</div>

		{{-- Menu --}}
		<div class="my-10 flex flex-grow flex-col overflow-y-auto">

			<h3 class="mb-4 font-heading text-xl">Menu</h3>
			<nav class="grid gap-4">
				@include('layouts.sidebar.parts.menu-items')
			</nav>
		</div>

		{{-- Logout button --}}
		<form class="mt-auto" method="POST" action="{{ route('logout') }}">
			@csrf

			<x-link type :href="route('logout')" component="button">
				{{ __('Log Out') }}
			</x-link>
		</form>
	</div>
</header>

resources/views/layouts/header/parts/menu-items.blade.php
		<x-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
		{{ __('Dashboard') }}
		</x-link>

		<x-link :href="route('profile.index')" :active="request()->routeIs('profile.profile')">
		{{ __('Profile') }}
		</x-link>

resources/views/layouts/sidebar/sidebar.blade.php
<div class="sticky top-[60px] hidden h-[calc(100dvh-60px)] bg-dark px-4 py-12 sm:block lg:px-8">
	<nav class="grid gap-4">
		@include('layouts.sidebar.parts.menu-items')
	</nav>
</div>

resources/views/video.blade.php
<x-app-layout>
	<x-container>

		<x-topbar class="mb-8">
			<x-slot:title>
				{{ __('Dashboard') }}
			</x-slot:title>
		</x-topbar>
        <div id="sh-list_video-9074"></div>
    </x-container>
</x-app-layout>

<script>
    $(function() {
        shMediaVideo({
            'key': '{{env('MEDIAHUB_KEY')}}',
            'cid': '29',
            'tags': '',
            'lang': 'en',
            'blockID': 'sh-list_video-9074'
        });
    });
</script>